placesremember/placesremember/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from placesremember import settings

from placesremember_app.views import pageNotFound

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("placesremember_app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

placesremember/placesremember_app/urls.py
from django.urls import path

from .views import (
    AddPlace,
    Home,
    LoginUser,
    RegisterUser,
    ShowPlace,
    about,
    logout_user,
)

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("about/", about, name="about"),
    path("add_place/", AddPlace.as_view(), name="add_place"),
    path("login/", LoginUser.as_view(), name="login"),
    path("logout/", logout_user, name="logout"),
    path("register/", RegisterUser.as_view(), name="register"),
    path("place/<int:place_id>/", ShowPlace.as_view(), name="place"),
]

placesremember/placesremember_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Place(models.Model):
    """Model for storing records of visited places"""

    title = models.CharField(max_length=250, blank=False, verbose_name="Place Title")
    photo = models.ImageField(
        upload_to="photos/", blank=True, verbose_name="Place Photo"
    )
    content = models.TextField(default="", blank=True, verbose_name="Comment")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Creation Time")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Change Time")
    user_id = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=False, verbose_name="User ID"
    )
    lon = models.FloatField(default=0.0)
    lat = models.FloatField(default=0.0)

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse("place", kwargs={"place_id": self.pk})

    class Meta:
        verbose_name = "Place"
        ordering = ["id"]

placesremember/placesremember_app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

from .models import Place


class AddPlaceForm(forms.ModelForm):
    """Form to add new place"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    lat = forms.FloatField(label="", widget=forms.HiddenInput(), required=False)
    lon = forms.FloatField(label="", widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Place
        fields = ["title", "content", "photo", "lat", "lon"]
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-input"}),
            "content": forms.Textarea(attrs={"cols": 60, "rows": 10}),
        }


class RegisterUserForm(UserCreationForm):
    """New user registration form"""

    username = forms.CharField(
        label="Login", widget=forms.TextInput(attrs={"class": "form-input"})
    )
    password1 = forms.CharField(
        label="Password", widget=forms.PasswordInput(attrs={"class": "form-input"})
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput(attrs={"class": "form-input"}),
    )

    class Meta:
        model = User
        fields = ("username", "password1", "password2")


class LoginUserForm(AuthenticationForm):
    """User authorization form"""

    username = forms.CharField(
        label="Login", widget=forms.TextInput(attrs={"class": "form-input"})
    )
    password = forms.CharField(
        label="Password", widget=forms.PasswordInput(attrs={"class": "form-input"})
    )

placesremember/placesremember_app/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponseNotFound
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView

from placesremember_app.forms import AddPlaceForm, LoginUserForm, RegisterUserForm
from placesremember_app.models import Place
from placesremember_app.utils import DataMixin

menu = [
    {"title": "Main Page", "url_name": "home"},
    {"title": "About", "url_name": "about"},
]


class Home(DataMixin, ListView):
    """View class to display authorized user places"""

    model = Place
    template_name = "index.html"
    context_object_name = "places"

    def get_queryset(self):
        return Place.objects.filter(user_id=self.request.user.pk)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user_data = self.get_user_context(title="Main Page", user_id=1)
        return dict(list(context.items()) + list(user_data.items()))


def about(request):
    """About site page"""

    context = {
        "menu": menu,
        "title": "About",
    }

    return render(request, "about.html", context)


class AddPlace(LoginRequiredMixin, DataMixin, CreateView):
    """View class to create new place by authorized user"""

    form_class = AddPlaceForm
    template_name = "add_place.html"
    success_url = reverse_lazy("home")
    login_url = reverse_lazy("home")
    raise_exception = True

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user_data = self.get_user_context(title="Add Place")
        return dict(list(context.items()) + list(user_data.items()))

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user_id = self.request.user
        self.object.save()
        return super(AddPlace, self).form_valid(form)


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = "login.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user_data = self.get_user_context(title="Sign In")
        return dict(list(context.items()) + list(user_data.items()))

    def get_success_url(self):
        return reverse_lazy("home")


class RegisterUser(DataMixin, CreateView):
    """View class to sign ip new user"""

    form_class = RegisterUserForm
    template_name = "register.html"
    success_url = reverse_lazy("login")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user_data = self.get_user_context(title="Sign Up")
        return dict(list(context.items()) + list(user_data.items()))

    def form_valid(self, form):
        user = form.save()
        login(self.request, user, backend="django.contrib.auth.backends.ModelBackend")
        return redirect("home")


class ShowPlace(DataMixin, DetailView):
    """View class that shows selected note"""

    model = Place
    template_name = "showplace.html"
    pk_url_kwarg = "place_id"
    context_object_name = "place"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        place_data = self.get_user_context(title=context["place"])
        return dict(list(context.items()) + list(place_data.items()))


def logout_user(request):
    logout(request)
    return redirect("home")


def pageNotFound(request, exception):
    return HttpResponseNotFound("<h1>Page Not Found</h1>")

placesremember/templates/about.html
{% extends 'base.html' %}

{% block content %}
<div class="container-item">
    <h1>{{ title }}</h1>
    <br>
    <h2>Contacts</h2>
    <br>
    <p>user@example.com</p>
</div>
<div id="map" style="width: 100%; height: 400px; margin-top: 100px;"></div>
<script>
    DG.then(function() {
        var map = DG.map('map', {
            center: [56.835059270477615, 60.612259137392066],
            zoom: 10
        });

        DG.marker([56.835059270477615, 60.612259137392066])
            .addTo(map)
            .bindPopup('example.com');
    });
</script>
{% endblock %}

placesremember/templates/add_place.html
{% extends 'base.html' %}

{% block content %}
<div class="container-item">
    <h1>{{ title }}</h1>
    <form class="form" action="{% url 'add_place' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for field in form %}
            <p><label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>{{ field }}</p>
            <div class="form-error">{{ field.errors }}</div>
            {% if field == lat %}
                <input type="hidden" name="lat" value="0.0" step="any" required="" id="id_lat">
                <input type="hidden" name="lon" value="0.0" step="any" required="" id="id_lon">
            {% endif %}
        {% endfor %}

        <h2>Mark the place on the map:</h2>
        <div id="map" style="width: 600px; height: 400px; margin-top: 10px;"></div>

        <script>
            let inputLat = document.querySelector('#id_lat');
            let inputLon = document.querySelector('#id_lon');
            DG.then(function() {
                var map = DG.map('map', {
                    center: [56.835059270477615, 60.612259137392066],
                    zoom: 10
                });


                map.on('click', (event) => {
                    inputLat.value = event.latlng.lat
                    inputLon.value = event.latlng.lng
                    marker = DG.marker([inputLat.value, inputLon.value])
                    .addTo(map)
                })
            });
        </script>

        <button class="submit-btn" type="submit">Add</button>


    </form>
    </div>
{% endblock %}

placesremember/templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <script src="https://maps.api.2gis.ru/2.0/loader.js?pkg=full"></script>

    <title>{{ title }}</title>
</head>
<body>

{% block mainmenu %}
<div class="header">
    <ul id="mainmenu" class="mainmenu">
        {% for tab in menu %}
            <li><a href="{% url tab.url_name %}">{{ tab.title }}</a></li>
        {% endfor %}
        {% if request.user.is_authenticated %}
            {% if not user.first_name %}
                <li class="last"> {{ user.username }} | <a href="{% url 'account_logout' %}">Log Out</a></li>
            {% else %}
                <li class="last"> {{ user.first_name }} | <a href="{% url 'account_logout' %}">Log Out</a></li>
            {% endif %}
        {% endif %}

    </ul>
    <div class="clear"></div>
</div>
{% endblock mainmenu %}

{% block content %}
{% endblock %}
</body>
</html>

placesremember/templates/index.html
{% extends 'base.html' %}

{% load socialaccount %}

{% block content %}
{% get_providers as socialaccount_providers %}

{% if not request.user.is_authenticated %}
    <div class="container-item">
        <br>
        <h1>Project Places Remember</h1>
        <br>
        <h3>Places Remember is a service for saving your memories.

            You can add entries about your big and small trips,
            with photos and your impressions,
            so that you can return to them later</h3>
        <br>
    </div>
    <div class="container-item">
        <br>
        <h2>You are not authorized! Sign with:</h2>
        <form class="form-vk-btn m-t-17" action="/accounts/vk/login/?process=login">
            <button class="vk-btn" type="submit"><img src="static/img/VK_Logo.png" alt="VK" height="50" width="50">VKontakte</button>
        </form>
        <br>
        <h2> OR use PlacesRemember account: </h2>
        <br>
        <form class="form-submit-btn m-t-17" action="{% url 'login' %}">
            <button class="submit-btn">Sign In</button>
        </form>
    </div>
    <div class="w-full text-center p-t-55">
        <span class="txt2">Not a member?</span>
        <a class="txt2 bo1" href="{% url 'register' %}" > Sign up now </a>
    </div>
{% else %}

    <ul class="list-places">
            <h1>My memories</h1>
            <form class="form-add-place-btn m-t-17" action="{% url 'add_place' %}">
                <button class="add-place-btn">+Add Place</button>
            </form>
        {% if not places %}
            <div class="container-item">
                <br>
                <h3>There are no memories, let's create one</h3>
            </div>
        {% else %}
            {% for place in places %}
                <li><h2>{{ place.title }}</h2>
                {% if place.photo %}
                    <p><img class="img-article-left thumb" src="{{ place.photo.url }}"></p>
                {% endif %}
                {{ place.time_create }}
                <br>
                {{ place.content|linebreaks|truncatewords:30}}
                <div class="clear"></div>
                <form class="form-show-place-btn m-t-17" action="{{ place.get_absolute_url }}">
                    <button class="show-place-btn">View</button>
                </form>
                </li>
            {% endfor %}
        {% endif %}
    {% endif %}
</ul>
{% endblock %}

placesremember/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container-item">
    <h1>{{ title }}</h1>
</div>

<form method="post">
    <div class="container-item">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for field in form %}
            <p><label class="form-label" for="{{ field.id_for_label }}">{{field.label}}: </label>{{ field }}</p>
            <div class="form-error">{{ field.errors }}</div>
        {% endfor %}
        <button class="submit-btn" type="submit">Sign In</button>
    </div>
</form>
{% endblock %}

placesremember/templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container-item">
    <h1>{{ title }}</h1>
</div>

<form method="post">
    <div class="container-item">
        {% csrf_token %}
        {% for field in form %}
            <p><label class="form-label" for="{{ field.id_for_label }}">{{field.label}}: </label>{{ field }}</p>
            <div class="form-error">{{ field.errors }}</div>
        {% endfor %}
        <button class="submit-btn" type="submit">Sign Up</button>
    </div>
</form>

{% endblock %}

placesremember/templates/showplace.html
{% extends 'base.html' %}
{% load account %}


{% block content %}
{% if request.user.id == place.user_id_id %}
    <div class="show-place">
       <h1 style="margin-left: 10px;">{{ place.title }}</h1>
        {% if place.photo %}
            <div class="place-photo">
                <p><img class="img-article-left thumb" src="{{ place.photo.url }}"></p>
            </div>
        {% endif %}
        <p>{{ place.content }}</p>
    </div>
    <br>

    <div id="map" style="width: 600px; height: 400px; position: relative; margin-top: 200px; margin-left: 10px;"></div>
    <script>
        DG.then(function() {
            var map = DG.map('map', {
                center: [{{ place.lat }}, {{ place.lon }}],
                zoom: 10
            });

            DG.marker([{{ place.lat }}, {{ place.lon }}])
                .addTo(map)
                .bindPopup('{{ place.title }}');
        });


    </script>
{% else %}
    <div class="container-item">
        <h1>You have no access to this post!</h1>
        <form class="form-submit-btn m-t-17" action="{% url 'home' %}">
            <button class="submit-btn">Go to Main</button>
        </form>
    </div>
{% endif %}
{% endblock %}